CREATE TABLE funcionarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricula VARCHAR(50) NOT NULL,
    nome VARCHAR(150) NOT NULL,
    email VARCHAR(254) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT uk_funcionarios_matricula UNIQUE (matricula)
);