CREATE TABLE marcacoes_ponto (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 funcionario_id BIGINT NOT NULL,
                                 tipo VARCHAR(30) NOT NULL,
                                 ocorrida_em TIMESTAMP WITH TIME ZONE NOT NULL,

                                 CONSTRAINT fk_marcacoes_funcionario
                                     FOREIGN KEY (funcionario_id)
                                         REFERENCES funcionarios (id)
);

CREATE INDEX idx_marcacoes_funcionario_ocorrida_em
    ON marcacoes_ponto (funcionario_id, ocorrida_em);